dist: focal
sudo: true

language: python

os:
  - linux

python:
  - 3.6
  - 3.7
  - 3.8
  - 3.9-dev

before_install:
  - sudo apt-get install -y zlib1g-dev
  - sudo apt-get install -y patchelf
  - python -m pip install -U pip
  - python -m pip install --progress-bar off requests Cython

before_script:
  - python setup.py install

script:
  - cd /tmp
  - python -m unittest openfst_python.test

notifications:
  email:
    on_success: change
    on_failure: always
